#Removes all items from being rendered on the ground!
Items:
    Global: false
    Worlds:
    - FirstWorld
    - SecondWorld
#Removes all experience orbs, from the ground!
Orbs:
    Global: false
    Worlds:
    - FirstWorld
    - SecondWorld